# Pipeline configuration

# --- Input
inputdir: "example_data"
genome_extension: "{genome}.fa" #change according to genome file extension
dbdir: "databases" 

# --- Output directory
outdir: "results" 
outdir_anno: "results/Annotation" 
logdir: "logs"

# Step 1: Genome Annotation
# --- Evalues:
cog_evalue: "1e-5"
pfam_evalue: "1e-5"

# --- Select databases to use
PFAM: True
COG: True
KEGG: True
CAZYMES: False
MEROPS: True
