# Pipeline configuration

# --- Input
inputdir: "example_data"
dbdir: "databases" 
nucleotide_extension: "{genome}.fa" #change according to genome file extension
aminoacid_extension: "{genome}.faa" #change according to genome file extension

# Input files are nucleotide or aminoacid files?
aminoacid_file: False #if True - gene calling (Prokka) won't be run

# Input files - other characteristics:
metagenome: False  #different setting in prokka?
unassembled_reads: False

# --- Output directory
outdir: "results" 
outdir_anno: "results/Annotation" 
logdir: "logs"

# --- Evalues:
cog_evalue: "1e-5" #for rpsblast
pfam_evalue: "1e-5" #for hmmsearch
merops_evalue: "1e-5" #for blastp
kegg_evalue: "1e-5" #for hmmsearch - implement

# --- Select databases to use
PFAM: True
COG: True
KEGG: True
CAZYMES: False
MEROPS: True

# Nr of threads/cores - implement
