# Pipeline configuration

# --- Input
inputdir: "example_data"
nucleotide_extension: "{genome}.fna" #change according to fasta nucleotide file extension
aminoacid_extension: "{genome}.fa" #change according to fasta aminoacid file extension
fastq_extension: "{genome}.fastq" #change according to Fastq file extension (if needed)

# Input files are nucleotide or aminoacid files?
file_type: "aminoacid" #OPTIONS: "nucleotide" "aminoacid"  "fastq"

# --- Output directory
outdir: "results" 
outdir_anno: "results/Annotation" 

# --- Select databases to use - True or False
PFAM: True
COG: True
KEGG: False
CAZYMES: False
MEROPS: False

# --- Evalues:
cog_evalue: "1e-5" #for rpsblast
pfam_evalue: "1e-5" #for hmmsearch
merops_evalue: "1e-5" #for blastp

# --- Nr of tools to consider for CAZymes annotation:
cazymes_tools: 3 #default is 3

# Nr of threads/cores - implement
