# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/sandragodinhosilva/melange" }

# gem "rails"
gem "jekyll"

group :jekyll_plugins do
    gem 'jekyll-google-tag-manager'
  end